### ISSUE TITLE
Cargo color differentiation

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#1]
This year there is a new challenge for controlling the game piece, making sure that the game piece is the color of our alliance so that we can score without having to worry about scoring points for the other team. 
This issue has been opened in order to find a solution to this problem, a few possible solutions include:
-  Vision 
- Sensor (i.e a color sensor) , in the intake or conveyor, or both

**Comment by katzuv** [comment]
In my opinion, vision processing code should be stored in another repository, but if you organize it well I guess it's fine.

**Comment by adamv17** [comment]
We'll do it in another repo, I just wanted to have it written down here.
