### ISSUE TITLE
Update CTRE dependency version

### ISSUE THREAD

**Issue by katzuv** [Galaxia5987/robot-2022#10]
As done in ba78eb0ad4478f839612a15b5a568f44971b35d2.

**Comment by adamv17** [comment]
I believe this has already been incorporated into the main branch, each branch only has to merge from main

**Comment by katzuv** [comment]
> I believe this has already been incorporated into the main branch, each branch only has to merge from main 

It's still important to make sure `main` has the most up-to-date dependencies. I'd delete these commits from other branches and merge `main` into them (that's how it should be done).
