### ISSUE TITLE
Check feasibility of using 2 RPIs on the robot

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#30]
Is this possible? 2 RPIs on the robot may have the problem of forcing another radio for them to be legal.

**Comment by vichik123** [comment]
Simply set a static IP adress for both rPi, connect them both to the switch, and the switch to the robot.

**Comment by katzuv** [comment]
Do you want to use two because one isn't powerful enough?

**Comment by vichik123** [comment]
We want to have 2 cameras on the robot, and processing both feeds with one rPi is simply not possible.

**Comment by katzuv** [comment]
> We want to have 2 cameras on the robot, and processing both feeds with one rPi is simply not possible.

Why? PhotoVision supports multiple cameras  ([souce](https://docs.photonvision.org/en/latest/docs/getting-started/about/advantages.html?highlight=Multiple#multi-camera-support)).

**Comment by adamv17** [comment]
> > We want to have 2 cameras on the robot, and processing both feeds with one rPi is simply not possible.
> 
> Why? PhotoVision supports multiple cameras ([souce](https://docs.photonvision.org/en/latest/docs/getting-started/about/advantages.html?highlight=Multiple#multi-camera-support)).

Yes, but we will be running different codes on the RPI one for target detection and one for cargo detection. We asked photonvision and they said that switching between codes may pose a problem. The RPI isn't strong enough to do both at the same time.

**Comment by katzuv** [comment]
So is it a performance issue? Or just things wouldn't work? Or both…

**Comment by adamv17** [comment]
More of a performance issue
