### ISSUE TITLE
Adam is alive

### ISSUE THREAD

**Issue by barel13** [Galaxia5987/robot-2022#37]
die boi die

**Comment by katzuv** [comment]
Please open a pull request to fix the issue.

**Comment by vichik123** [comment]
This issue doesn't really involve any code.

**Comment by katzuv** [comment]
> This issue doesn't really involve any code.

What about path following, with Adam being on one of the waypoints?

**Comment by mandelete** [comment]
hmm very intewesting

**Comment by adamv17** [comment]
This is fine

**Comment by mandelete** [comment]
ah yes
die

**Comment by vichik123** [comment]
> > This issue doesn't really involve any code.
> 
> What about path following, with Adam being on one of the waypoints?

The path weaving usually doesn't allow for high speeds, so unaliving Adam by having him as one of the waypoints isn't very effective.

**Comment by vichik123** [comment]
Lady and gentlemen the issue is resolved.
