### ISSUE TITLE
Learn how to use ADIS gyro

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#55]
We got [this ](https://www.analog.com/en/products/ADIS16470.html)new gyro from first choice and it is on its way. 
[Update ](https://docs.wpilib.org/en/stable/docs/yearly-overview/known-issues.html)currently a known image in the new roborio image is a problem with the analog port which may make using the adis right now impossible.

**Comment by katzuv** [comment]
If you have a roboRIO with old firmware (or can downgrade one) you may be able to work with the gyro (with downgraded WPILib as well).

**Comment by vichik123** [comment]
ADIS? Don't you mean....... ADIDAS????
