### ISSUE TITLE
Update the port numbers

### ISSUE THREAD

**Issue by barel13** [Galaxia5987/robot-2022#60]

**Comment by katzuv** [comment]
If [I understand the issue](https://youtu.be/vb1w_1PuWGE?t=18), you want to update IDs of hardware components? If so, the following list is useful – each team member should update what's needed in their subsystem, then update the list:
- [x] Swerve
- [x] Intake
- [x] Conveyor
- [x] Shooter
- [x] Climber

**Comment by adamv17** [comment]
See this [link](https://docs.google.com/spreadsheets/d/1i6RU5gSvJDiIdLRgd-s03hMzk_nAkGQ5/edit?usp=sharing&ouid=117440682596909572731&rtpof=true&sd=true) for all the motor and solenoid ports.

**Comment by adamv17** [comment]
> 

well played with the link

**Comment by adamv17** [comment]
@katzuv well played with the link

**Comment by vichik123** [comment]
Not a rickroll [rickroll](https://www.youtube.com/watch?v=AyOqGRjVtls)
