### ISSUE TITLE
Test Intake Subsystem

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#72]
Add below a checklist for checking the intake subsystem.

**Comment by vichik123** [comment]
Testing for the intake:
- [ ] Check the direction of both the solenoid and the motor.
- [ ] Check the solidity of opening and closing the intake. If the intake can't withstand constant opening and closing cry and call your mommy. BIT test: Retractor Test
- [ ] Check time between opening and closing and the opposite.
- [ ] Try intaking and taking out balls from the intake, if the ball bounces off try lowering the velocity. If the intake doesn't work (from a mechanical standpoint) cry and call your mommy.
- [ ] Check the psi for opening and closing the intake.
- [ ] Check how many balls can go into the intake at once (if they do).
- [ ] Check whether it's possible to store balls inside the intake (could be useful strategically).
