### ISSUE TITLE
Test Conveyor Subsystem

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#74]
Add a checklist for checking the conveyor here.

**Comment by vichik123** [comment]
Tests for conveyor:
- [ ] Push as many balls as you can into the conveyor and check the stress on the belts.
- [ ] Check how conveyor works in conveying the balls (check whether they slip).
- [ ] Check the sensors.
- [ ] Check the flap to see if it keeps the balls away from the shooter.
- [ ] Dependency on the intake.
- [ ] Check the strength of the pulleys by putting 100% power.
