### ISSUE TITLE
BIT command group

### ISSUE THREAD

**Issue by adamv17** [Galaxia5987/robot-2022#78]
At one point it may be extremely helpful to have a bit for the entire robot which checks autonomously whether the robot can enter the field.

**Comment by vichik123** [comment]
The problem with making a bit for the entire robot is testing the odometry. I don't know if we're allowed to drive the robot on the ground before entering the field. However, perhaps it would be beneficial to test all the other subsystems with the bit I have written in the `feature/command-groups-bits` pull request.

**Comment by katzuv** [comment]
@littlebro123, if I understand @adamv17's idea, "can enter the field" means the robot is working as expected. In that case, I don't think you need to test the odometry. It's code, not something physical that can malfunction between matches. You _can_ check whether the encoders work as expected.
Also, just so you know, you can reference pull requests and issues with a hashtag, like that: #86. 

I agree that running the command group tests is great, I'd like to continue the conversation from [here](https://github.com/Galaxia5987/robot-2022/pull/66#discussion_r800094972) (I think this issue fits).
> @adamv17: Yes we will add bits for each subsystem, how would you handle a TODO list?

Create a large command group that will run the bits one after the other. You might need to modify them a bit to log whether the test has succeeded or not.
