### ISSUE TITLE
Delete example subsystem files

### ISSUE THREAD

**Issue by katzuv** [Galaxia5987/robot-2022#8]

**Comment by katzuv** [comment]
@adamv17, it's important to close each issue with a relevant pull request to follow issues status. There are two ways to do that:
- [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- Another way is to include the keywords mentioned in the article above in the relevant commit message: i.e. "Delete example subsystem files (closes #8)".

Also, was the deletion committed directly to `main`? This should never be done. I would make `main` a protected branch, which will prevent commiting to it directly.
Every change, no matter how small it is (even if it's only a single commit), should be added in a different branch, them merged via a pull request.

This might seem like a waste of time, but especially in a fast-paced environment like FRC, where bad changes might be made quickly and carelessly, it's important to work in an orderly manner to make sure those mistakes  can be easily reverted.

**Comment by adamv17** [comment]
Okay you are right I'll do that next time
